/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Library.Objetos;
import ViewModels.ClientesVM;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpnlPrincipal = new javax.swing.JTabbedPane();
        pnlVentas = new javax.swing.JPanel();
        pnlClientes = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        TabbedPaneCliente1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlFotoCliente = new javax.swing.JPanel();
        lblFotoCliente = new javax.swing.JLabel();
        lblClienteDni = new javax.swing.JLabel();
        txtClienteDni = new javax.swing.JTextField();
        lblClienteNom = new javax.swing.JLabel();
        txtClienteNom = new javax.swing.JTextField();
        lblClienteApe = new javax.swing.JLabel();
        txtClienteApe = new javax.swing.JTextField();
        lblClienteEmail = new javax.swing.JLabel();
        txtClienteEmail = new javax.swing.JTextField();
        lblClienteDir = new javax.swing.JLabel();
        txtClienteTel = new javax.swing.JTextField();
        txtClienteDir = new javax.swing.JTextField();
        CheckBoxCliente_Credito = new javax.swing.JCheckBox();
        lblClienteTel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnClienteAdd = new javax.swing.JButton();
        txtClienteCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        TabbedPaneCliente2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = tableClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false; //Disable the editing of any cell
            }
        };
        jPanel8 = new javax.swing.JPanel();
        lblClienteTel = new javax.swing.JLabel();
        spnClientes_Paginas = new javax.swing.JSpinner();
        btnCliente_First = new javax.swing.JButton();
        labelCliente_Paginas = new javax.swing.JLabel();
        btnCliente_Prev = new javax.swing.JButton();
        btnCliente_Next = new javax.swing.JButton();
        btnCliente_Last = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        tpnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        tpnlPrincipal.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tpnlPrincipal.setPreferredSize(new java.awt.Dimension(1108, 500));

        pnlVentas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlVentasLayout = new javax.swing.GroupLayout(pnlVentas);
        pnlVentas.setLayout(pnlVentasLayout);
        pnlVentasLayout.setHorizontalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
        );
        pnlVentasLayout.setVerticalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        tpnlPrincipal.addTab("Ventas", pnlVentas);

        pnlClientes.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Clientes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Buscar:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TabbedPaneCliente1.setBackground(new java.awt.Color(255, 255, 255));
        TabbedPaneCliente1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneCliente1StateChanged(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Información cliente");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, -1));

        pnlFotoCliente.setBackground(new java.awt.Color(255, 255, 255));

        lblFotoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_user_127px.png"))); // NOI18N
        lblFotoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lblFotoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFotoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlFotoClienteLayout = new javax.swing.GroupLayout(pnlFotoCliente);
        pnlFotoCliente.setLayout(pnlFotoClienteLayout);
        pnlFotoClienteLayout.setHorizontalGroup(
            pnlFotoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFotoClienteLayout.setVerticalGroup(
            pnlFotoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(pnlFotoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 150, -1));

        lblClienteDni.setBackground(new java.awt.Color(255, 255, 255));
        lblClienteDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClienteDni.setForeground(new java.awt.Color(102, 102, 102));
        lblClienteDni.setText("DNI");
        jPanel6.add(lblClienteDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtClienteDni.setToolTipText("");
        txtClienteDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteDniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteDniKeyTyped(evt);
            }
        });
        jPanel6.add(txtClienteDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 190, -1));

        lblClienteNom.setBackground(new java.awt.Color(255, 255, 255));
        lblClienteNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClienteNom.setForeground(new java.awt.Color(102, 102, 102));
        lblClienteNom.setText("Nombre");
        jPanel6.add(lblClienteNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtClienteNom.setToolTipText("");
        txtClienteNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteNomKeyTyped(evt);
            }
        });
        jPanel6.add(txtClienteNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, -1));

        lblClienteApe.setBackground(new java.awt.Color(255, 255, 255));
        lblClienteApe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClienteApe.setForeground(new java.awt.Color(102, 102, 102));
        lblClienteApe.setText("Apellidos");
        jPanel6.add(lblClienteApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtClienteApe.setToolTipText("");
        txtClienteApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteApeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteApeKeyTyped(evt);
            }
        });
        jPanel6.add(txtClienteApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, -1));

        lblClienteEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblClienteEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClienteEmail.setForeground(new java.awt.Color(102, 102, 102));
        lblClienteEmail.setText("Email");
        jPanel6.add(lblClienteEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtClienteEmail.setToolTipText("");
        txtClienteEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteEmailKeyTyped(evt);
            }
        });
        jPanel6.add(txtClienteEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 158, -1));

        lblClienteDir.setBackground(new java.awt.Color(255, 255, 255));
        lblClienteDir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClienteDir.setForeground(new java.awt.Color(102, 102, 102));
        lblClienteDir.setText("Dirección");
        jPanel6.add(lblClienteDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtClienteTel.setToolTipText("");
        txtClienteTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteTelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteTelKeyTyped(evt);
            }
        });
        jPanel6.add(txtClienteTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, -1));

        txtClienteDir.setToolTipText("");
        txtClienteDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteDirKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteDirKeyTyped(evt);
            }
        });
        jPanel6.add(txtClienteDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 330, -1));

        CheckBoxCliente_Credito.setText("Crédito");
        jPanel6.add(CheckBoxCliente_Credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        lblClienteTel1.setBackground(new java.awt.Color(255, 255, 255));
        lblClienteTel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblClienteTel1.setForeground(new java.awt.Color(102, 102, 102));
        lblClienteTel1.setText("Teléfono");
        jPanel6.add(lblClienteTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        TabbedPaneCliente1.addTab("Registro de clientes", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        TabbedPaneCliente1.addTab("Pagos y Reportes", jPanel7);

        btnClienteAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_plus_+_24px.png"))); // NOI18N
        btnClienteAdd.setText("Agregar");
        btnClienteAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClienteAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAddActionPerformed(evt);
            }
        });

        txtClienteCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_cancel_24px_1.png"))); // NOI18N
        txtClienteCancel.setText("Cancelar");
        txtClienteCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtClienteCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneCliente1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnClienteAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClienteCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(TabbedPaneCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClienteCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TabbedPaneCliente2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneCliente2StateChanged(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientesMouseClicked(evt);
            }
        });
        tableClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableClientes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        TabbedPaneCliente2.addTab("Lista de Clientes", jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        TabbedPaneCliente2.addTab("Pagos y Reportes", jPanel8);

        lblClienteTel.setBackground(new java.awt.Color(255, 255, 255));
        lblClienteTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblClienteTel.setForeground(new java.awt.Color(102, 102, 102));
        lblClienteTel.setText("Registros por páginas");

        spnClientes_Paginas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnClientes_PaginasStateChanged(evt);
            }
        });

        btnCliente_First.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_double_left_20px_3.png"))); // NOI18N
        btnCliente_First.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCliente_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente_FirstActionPerformed(evt);
            }
        });

        labelCliente_Paginas.setBackground(new java.awt.Color(255, 255, 255));
        labelCliente_Paginas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCliente_Paginas.setForeground(new java.awt.Color(102, 102, 102));
        labelCliente_Paginas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCliente_Paginas.setText("Páginas");

        btnCliente_Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_back_20px.png"))); // NOI18N
        btnCliente_Prev.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCliente_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente_PrevActionPerformed(evt);
            }
        });

        btnCliente_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_forward_20px.png"))); // NOI18N
        btnCliente_Next.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCliente_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente_NextActionPerformed(evt);
            }
        });

        btnCliente_Last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_double_right_20px_5.png"))); // NOI18N
        btnCliente_Last.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCliente_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente_LastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneCliente2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClienteTel)
                    .addComponent(spnClientes_Paginas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCliente_First, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCliente_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCliente_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCliente_Last, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelCliente_Paginas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(TabbedPaneCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteTel)
                    .addComponent(labelCliente_Paginas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCliente_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente_Prev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente_Last, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCliente_First, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnClientes_Paginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, Short.MAX_VALUE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        tpnlPrincipal.addTab("Clientes", pnlClientes);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_users_28px.png"))); // NOI18N
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="CODIGO DE CLIENTE">
    private ClientesVM cliente;
    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        
        ArrayList<JLabel> label = new ArrayList();
        label.add(lblClienteDni);
        label.add(lblClienteNom);
        label.add(lblClienteApe);
        label.add(lblClienteEmail);
        label.add(lblClienteTel);
        label.add(lblClienteDir);
        label.add(lblFotoCliente);
        label.add(labelCliente_Paginas);        
        ArrayList<JTextField> textField = new ArrayList();
        textField.add(txtClienteDni);
        textField.add(txtClienteNom);
        textField.add(txtClienteApe);
        textField.add(txtClienteEmail);
        textField.add(txtClienteTel);
        textField.add(txtClienteDir);
        Object[] objects = {
            CheckBoxCliente_Credito,
            tableClientes,
            spnClientes_Paginas
        };
        cliente = new ClientesVM(objects, label, textField);
        
        tpnlPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void lblFotoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoClienteMouseClicked
        Objetos.uploadImage.CargarImagen(lblFotoCliente);
    }//GEN-LAST:event_lblFotoClienteMouseClicked

    private void txtClienteDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteDniKeyReleased
        if(txtClienteDni.getText().equals("")){
            lblClienteDni.setForeground(new Color(102, 102, 102));
        }else{
            lblClienteDni.setText("DNI");
            lblClienteDni.setForeground(new Color(0, 153, 51));
            
        }
    }//GEN-LAST:event_txtClienteDniKeyReleased

    private void txtClienteDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteDniKeyTyped
        Objetos.eventos.numberKeyPress(evt);
    }//GEN-LAST:event_txtClienteDniKeyTyped

    private void txtClienteNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteNomKeyReleased
        if(txtClienteNom.getText().equals("")){
            lblClienteNom.setForeground(new Color(102, 102, 102));
        }else{
            lblClienteNom.setText("Nombre");
            lblClienteNom.setForeground(new Color(0, 153, 51));
            
        }
    }//GEN-LAST:event_txtClienteNomKeyReleased

    private void txtClienteNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteNomKeyTyped
        Objetos.eventos.textKeyPress(evt);
    }//GEN-LAST:event_txtClienteNomKeyTyped

    private void txtClienteApeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteApeKeyReleased
        if(txtClienteApe.getText().equals("")){
            lblClienteApe.setForeground(new Color(102, 102, 102));
        }else{
            lblClienteApe.setText("Apellido");
            lblClienteApe.setForeground(new Color(0, 153, 51));
            
        }
    }//GEN-LAST:event_txtClienteApeKeyReleased

    private void txtClienteApeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteApeKeyTyped
        Objetos.eventos.textKeyPress(evt);
    }//GEN-LAST:event_txtClienteApeKeyTyped

    private void txtClienteEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteEmailKeyReleased
        if(txtClienteEmail.getText().equals("")){
            lblClienteEmail.setForeground(new Color(102, 102, 102));
        }else{
            lblClienteEmail.setText("Email");
            lblClienteEmail.setForeground(new Color(0, 153, 51));
            
        }
    }//GEN-LAST:event_txtClienteEmailKeyReleased

    private void txtClienteEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteEmailKeyTyped

    private void txtClienteTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteTelKeyReleased
        if(txtClienteTel.getText().equals("")){
            lblClienteTel.setForeground(new Color(102, 102, 102));
        }else{
            lblClienteTel.setText("Teléfono");
            lblClienteTel.setForeground(new Color(0, 153, 51));
            
        }
    }//GEN-LAST:event_txtClienteTelKeyReleased

    private void txtClienteTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteTelKeyTyped
        Objetos.eventos.numberKeyPress(evt);
    }//GEN-LAST:event_txtClienteTelKeyTyped

    private void txtClienteDirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteDirKeyReleased
        if(txtClienteDir.getText().equals("")){
            lblClienteDir.setForeground(new Color(102, 102, 102));
        }else{
            lblClienteDir.setText("Dirección");
            lblClienteDir.setForeground(new Color(0, 153, 51));
            
        }
    }//GEN-LAST:event_txtClienteDirKeyReleased

    private void txtClienteDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteDirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteDirKeyTyped

    private void btnClienteAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAddActionPerformed
        cliente.RegistrarCliente();
    }//GEN-LAST:event_btnClienteAddActionPerformed

    private void txtClienteCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteCancelActionPerformed
        cliente.restablecer();
    }//GEN-LAST:event_txtClienteCancelActionPerformed

    private void btnCliente_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente_FirstActionPerformed
        cliente.Paginador("Primero");
    }//GEN-LAST:event_btnCliente_FirstActionPerformed

    private void btnCliente_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente_PrevActionPerformed
        cliente.Paginador("Anterior");
    }//GEN-LAST:event_btnCliente_PrevActionPerformed

    private void btnCliente_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente_NextActionPerformed
        cliente.Paginador("Siguiente");
    }//GEN-LAST:event_btnCliente_NextActionPerformed

    private void btnCliente_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente_LastActionPerformed
        cliente.Paginador("Ultimo");
    }//GEN-LAST:event_btnCliente_LastActionPerformed

    private void spnClientes_PaginasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnClientes_PaginasStateChanged
        cliente.Registro_Paginas();
    }//GEN-LAST:event_spnClientes_PaginasStateChanged

    private void tableClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableClientesKeyReleased
        if (tableClientes.getSelectedRows().length > 0){
            cliente.GetCliente();
        }
    }//GEN-LAST:event_tableClientesKeyReleased

    private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseClicked
        if (tableClientes.getSelectedRows().length > 0){
            cliente.GetCliente();
        }
    }//GEN-LAST:event_tableClientesMouseClicked

    private void TabbedPaneCliente1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneCliente1StateChanged
        if (TabbedPaneCliente1.getSelectedIndex() == 0){
            if(TabbedPaneCliente2.getSelectedIndex() > 0){
                TabbedPaneCliente2.setSelectedIndex(0);
            }
        }else{
            TabbedPaneCliente2.setSelectedIndex(1);
        }
    }//GEN-LAST:event_TabbedPaneCliente1StateChanged

    private void TabbedPaneCliente2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneCliente2StateChanged
        if (TabbedPaneCliente2.getSelectedIndex() == 0){
            if(TabbedPaneCliente1.getSelectedIndex() > 0){
                TabbedPaneCliente1.setSelectedIndex(0);
            }
        }else{
            TabbedPaneCliente1.setSelectedIndex(1);
        }
    }//GEN-LAST:event_TabbedPaneCliente2StateChanged
    
    // </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxCliente_Credito;
    private javax.swing.JTabbedPane TabbedPaneCliente1;
    private javax.swing.JTabbedPane TabbedPaneCliente2;
    private javax.swing.JButton btnClienteAdd;
    private javax.swing.JButton btnCliente_First;
    private javax.swing.JButton btnCliente_Last;
    private javax.swing.JButton btnCliente_Next;
    private javax.swing.JButton btnCliente_Prev;
    private javax.swing.JButton btnClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCliente_Paginas;
    private javax.swing.JLabel lblClienteApe;
    private javax.swing.JLabel lblClienteDir;
    private javax.swing.JLabel lblClienteDni;
    private javax.swing.JLabel lblClienteEmail;
    private javax.swing.JLabel lblClienteNom;
    private javax.swing.JLabel lblClienteTel;
    private javax.swing.JLabel lblClienteTel1;
    private javax.swing.JLabel lblFotoCliente;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlFotoCliente;
    private javax.swing.JPanel pnlVentas;
    private javax.swing.JSpinner spnClientes_Paginas;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTabbedPane tpnlPrincipal;
    private javax.swing.JTextField txtClienteApe;
    private javax.swing.JButton txtClienteCancel;
    private javax.swing.JTextField txtClienteDir;
    private javax.swing.JTextField txtClienteDni;
    private javax.swing.JTextField txtClienteEmail;
    private javax.swing.JTextField txtClienteNom;
    private javax.swing.JTextField txtClienteTel;
    // End of variables declaration//GEN-END:variables
}
